app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Admin routes
|--------------------------------------------------------------------------
*/
Route::match(['GET', 'POST'], '/auth', [
    'prefix' => 'backend',
    'as' => 'backend.auth.login',
    'uses' => 'Backend\User\AuthController@login',
    'middleware' => ['web', 'language:backend', 'backend', 'setTheme:backend']
]);

Route::group(['prefix' => 'backend', 'namespace' => 'Backend', 'middleware' => ['web', 'language:backend', 'backend', 'auth:backend', 'setTheme:backend']], function () {

    // Site
    Route::get('/', ['as' => 'backend.site.index', 'uses' => 'SiteController@index']);
    Route::get('/page/logs', ['as' => 'backend.site.logs', 'uses' => 'SiteController@logs']);
    Route::match(['GET', 'POST'], '/page/settings', ['as' => 'backend.site.settings', 'uses' => 'SiteController@settings']);


    // Languages
    Route::get('/set-lang/{lang}', ['as' => 'backend.site.set-lang', 'uses' => 'SiteController@setLang']);
    Route::get('/languages/translations/{id}', ['as' => 'backend.languages.translations', 'uses' => 'LanguagesController@translations']);
    Route::put('/languages/translationUpdate', ['as' => 'backend.languages.translationsUpdate', 'uses' => 'LanguagesController@translationsUpdate']);

    // Modules
    Route::resource('contents', 'ContentsController');
    Route::resource('cities', 'CitiesController');
    // Route::resource('widgets', 'WidgetsController');
    Route::resource('seo', 'SeoController');
    Route::resource('languages', 'LanguagesController');
    Route::resource('currencies', 'CurrenciesController');
    //Route::resource('access', 'AccessController');
    Route::resource('reviews', 'ReviewsController');

    // Plugins
    Route::resource('plugins', 'PluginsController');
    Route::get('/plugins/control/{id}', [
        'as' => 'backend.plugins.control',
        'uses' => 'PluginsController@control'
    ]);

    // Content Extra
    Route::post('/contents/upload', ['as' => 'backend.contents.upload', 'uses' => 'ContentsController@upload']);
    Route::post('/contents/upload/images/{content}', ['as' => 'backend.content.images.upload', 'uses' => 'ContentImagesController@upload']);
    Route::resource('contentImages', 'ContentImagesController', ['only' => [
        'edit', 'update', 'destroy'
    ]]);

    // Help
    Route::get('/help', ['as' => 'backend.help.index', 'uses' => 'HelpController@index']);

    // Shop
    Route::group(['prefix' => 'shop', 'namespace' => 'Shop'], function ()
    {
        Route::get('/filter', ['as' => 'backend.shop.filter.index', 'uses' => 'FilterController@index']);

        Route::resource('checkoutProducts', 'CheckoutProductsController', ['only' => [
            'index', 'store', 'update', 'destroy'
        ]]);

        Route::resource('categories', 'CategoriesController');
        Route::resource('checkouts', 'CheckoutsController');
        Route::resource('coupons', 'CouponsController');
        Route::resource('landings', 'LandingsController');
        Route::resource('discounts', 'DiscountsController');
        Route::resource('products', 'ProductsController');
        Route::post('/products/{id}/files', ['as' => 'backend.products.files', 'uses' => 'ProductsController@files']);
        Route::post('/products/{id}/filter', ['as' => 'backend.products.filter', 'uses' => 'ProductsController@filter']);
        Route::post('/products/{id}/filter-param', ['as' => 'backend.products.filter.param', 'uses' => 'ProductsController@filterParam']);

        Route::resource('properties', 'PropertiesController', ['only' => [
            'index', 'create', 'store', 'edit', 'update', 'destroy'
        ]]);
        Route::resource('values', 'ValuesController', ['only' => [
            'store', 'update', 'destroy', 'create', 'edit'
        ]]);
        Route::resource('images', 'ImagesController', ['only' => [
            'edit', 'update', 'destroy'
        ]]);
        Route::post('/{id}/images/upload', ['as' => 'backend.shop.images.upload', 'uses' => 'ImagesController@upload']);
        Route::post('/{id}/images/order', ['as' => 'backend.shop.images.order', 'uses' => 'ImagesController@order']);
    });

    // Media
    Route::group(['prefix' => 'media', 'namespace' => 'Media'], function ()
    {
        Route::resource('videos', 'VideosController');
        Route::resource('images', 'ImagesController', ['only' => [
            'index', 'edit', 'update', 'destroy'
        ]]);
        Route::post('/images/upload', ['as' => 'backend.media.images.upload', 'uses' => 'ImagesController@upload']);
    });

    // User
    Route::group(['prefix' => 'user', 'namespace' => 'User'], function ()
    {
        // Auth
        Route::get('/logout', ['as' => 'backend.auth.logout', 'uses' => 'AuthController@logout']);

        Route::resource('users', 'UsersController');
        Route::post('users/{id}/restore', 'UsersController@restore')->name('backend.user.users.restore');
    });

    Route::group(['prefix' => 'plugins', 'namespace' => 'Plugins'], function () {

        // Slider
        Route::get('/slider/edit/{id}', [
            'as' => 'backend.plugins.slider.edit',
            'uses' => '\App\Plugins\Slider\Backend\SliderController@edit'
        ]);
        Route::post('/slider/update/{id}', [
            'as' => 'backend.plugins.slider.update',
            'uses' => '\App\Plugins\Slider\Backend\SliderController@update'
        ]);

        Route::get('/slider/destroy/{id}', [
            'as' => 'backend.plugins.slider.destroy',
            'uses' => '\App\Plugins\Slider\Backend\SliderController@destroy'
        ]);

        Route::resource('text', '\App\Plugins\Text\Backend\TextController');
    });

});

/*
|--------------------------------------------------------------------------
| App routes
|--------------------------------------------------------------------------
*/
Route::group(['middleware' => ['guest', 'web']], function () {
    Route::group(['prefix' => 'signin', 'as' => 'guest.'], function () {
        Route::get('{profile_type}', 'OAuthController@redirectToProvider')->name('oauth.redirect');
        Route::get('{profile_type}/callback', 'OAuthController@handleProviderCallback')->name('oauth.callback');
        Route::post('{profile_type}/signup', 'OAuthController@auth')->name('oauth.signup');
    });
});

$frontend_attr = ['middleware' => ['web', 'frontend', 'language:frontend', 'setTheme:default']];
$locale = Request::segment(1);

if(Translate::getLangByLocale($locale) && empty(Translate::getLangByLocale($locale)['default'])) {
    $frontend_attr['prefix'] = $locale;
}


//TODO: fix this route (same route in Payment group doesn't work)

Route::match(['get', 'post'], '/platon/callback', ['as' => 'platon.callback', 'uses' => 'Payment\PlatonController@callback']);

Route::group($frontend_attr, function () {

    // Site
    Route::get('/badbrowser', ['as' => 'site.badbrowser', 'uses' => 'SiteController@badbrowser']);
    Route::get('/contacts', ['as' => 'pages.contacts', 'uses' => 'SiteController@getContacts']);
    //Route::get('/sitemap.xml', ['as' => 'site.sitemap', 'uses' => 'SiteController@sitemap']);
    Route::get('/statics/js-data', ['uses' => 'SiteController@jsData']);

    Route::post('/contacts', ['as' => 'pages.contacts', 'uses' => 'SiteController@postContacts']);

    Route::get('/photos', ['as' => 'pages.photos', 'uses' => 'SiteController@photos']);
    Route::get('/videos', ['as' => 'pages.videos', 'uses' => 'SiteController@videos']);
    Route::get('/customorder', ['as' => 'pages.customorder', 'uses' => 'SiteController@getСustomorder']);
    Route::post('/customorder', ['as' => 'pages.customorder', 'uses' => 'SiteController@postСustomorder']);

    Route::get('/set-curr/{curr}', ['as' => 'site.set-curr', 'uses' => 'SiteController@setCurrency']);

    Route::get('/search', ['as' => 'product.search', 'uses' => 'ProductController@getSearch']);

    Route::get('/404.html', ['as' => 'error.404', 'uses' => 'SiteController@notFound']);



    Route::group(['middleware' => ['guest']], function () {

        // Login
        Route::get('/signin', ['uses' => 'GuestController@getSignin', 'as' => 'guest.signin']);
        Route::post('/signin', ['uses' => 'GuestController@postSignin', 'as' => 'guest.signin']);

        // Registration
        Route::get('/signup', ['uses' => 'GuestController@getSignup', 'as' => 'guest.signup']);
        Route::post('/signup', ['uses' => 'GuestController@postSignup', 'as' => 'guest.signup']);

        // Password Reset
        Route::get('/password/reset/{token?}', ['uses' => 'GuestController@getReset', 'as' => 'guest.password-reset']);
        Route::post('/password/email', ['uses' => 'GuestController@postEmail', 'as' => 'guest.password-email']);
        Route::post('/password/reset', ['uses' => 'GuestController@postReset', 'as' => 'guest.password-reset']);
    });

    // Email Confirmation Form
    Route::get('/signup/email-confirmation', [
        'uses' => 'GuestController@getConfirmForm',
        'as' => 'email_confirmation_form'
    ]);

    // Email Confirmation
    Route::get('/signup/email-confirm', [
        'uses' => 'GuestController@getConfirm',
        'as' => 'email_confirm'
    ]);

    Route::post('/buy-now', ['as' => 'cart.buy-now', 'uses' => 'CartController@postBuyNow']);

    Route::group(['middleware' => ['auth:web']], function () {
        // Аккаунт
        Route::get('/account', ['as' => 'user.index', 'uses' => 'UserController@index']);
        Route::post('/main-info', ['as' => 'user.main-info', 'uses' => 'UserController@postMainInfo']);
        Route::post('/manage-password', ['as' => 'user.manage-password', 'uses' => 'UserController@postManagePassword']);
        Route::post('/change-email', ['as' => 'user.change-email', 'uses' => 'UserController@postChangeEmail']);

        // История заказов

app/Models/Eloquent/Shop/Belongs/CategoriesProperties.php
<?php

namespace App\Models\Shop\Belongs;

/**
 * Categories Properties
 * @package App\Models\Shop
 */
class CategoriesProperties extends \App\Models\Model
{
    /**
     * @var string
     */
    protected $table = 'shop_categories_properties';

    /**
     * @return int
     */
    public function getPropertyId(): int
    {
        return $this->property_id ?? 0;
    }
}

app/Models/Eloquent/Shop/Belongs/ProductCategories.php
<?php

namespace App\Models\Shop\Belongs;

/**
 * Product Categories
 * @package App\Models\Shop
 */
class ProductCategories extends \App\Models\Model
{
    /**
     * @var string
     */
    protected $table = 'shop_product_categories';

    /**
     * @var bool
     */
    public $timestamps = false;
}

app/Models/Eloquent/Shop/Belongs/PropertiesValues.php
<?php

namespace App\Models\Shop\Belongs;

/**
 * Properties Values
 * @package App\Models\Shop\Belongs
 */
class PropertiesValues extends \App\Models\Model
{
    /**
     * @var string
     */
    protected $table = 'shop_properties_values';

    /**
     * @var bool
     */
    public $timestamps = false;
}

app/Models/Eloquent/Shop/Cart.php
<?php

namespace App\Models\Shop;

use App\Models\User\User;

/**
 * Cart
 * @package App\Models\Shop
 */
class Cart extends \App\Models\Model
{
    const COOKIE_MINUTES_EXPIRES = 30;

    /**
     * @var string
     */
    protected $table = 'shop_cart';

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function user()
    {
        return $this->hasOne(User::class, 'id', 'user_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function checkout()
    {
        return $this->hasOne(Checkout::class, 'cart_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function products()
    {
        return $this->hasMany(CartProducts::class, 'cart_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function productModels()
    {
        return $this->belongsToMany(Product::class, 'shop_cart_products', 'cart_id', 'product_id');
    }

    /**
     * Все данные карзины
     *
     * @param $query
     * @return mixed
     */
    public function scopeTotal($query)
    {
        $query->with(['products' => function ($query) {
            $query->with(['product'  => function ($query) {
                $query->translates();
            }]);
        }]);
    }

    /**
     * Сортировка DESC
     *
     * @param $query
     * @return mixed
     */
    public function scopeOrderDesc($query)
    {
        return $query->orderBy('created_at', 'desc');
    }

    /**
     * Сортировка ASC
     *
     * @param $query
     * @return mixed
     */
    public function scopeOrderAsc($query)
    {
        return $query->orderBy('created_at', 'asc');
    }

    /**
     * Сортировка ASC
     *
     * @param $query
     * @param int $state
     * @return mixed
     */
    public function scopeProcessed($query, $state = 1)
    {
        return $query->where('processed', $state);
    }

    public function isPaymentSystemAllowed($paymentSystem)
    {
        foreach ($this->productModels as $product) {
            if (! $product->hasPaymentSystem($paymentSystem)) {
                return false;
            }
        }

        return true;
    }
}

app/Models/Eloquent/Shop/CartProducts.php
<?php

namespace App\Models\Shop;

/**
 * Cart Products
 * @package App\Models\Shop
 */
class CartProducts extends \App\Models\Model
{
    /**
     * @var string
     */
    protected $table = 'shop_cart_products';

    /**
     * @var bool
     */
    public $timestamps = false;

    /**
     * @return \Illuminate\Database\Eloquent\Relations\hasOne
     */
    public function product()
    {
        return $this->hasOne(Product::class, 'id', 'product_id');
    }
}

app/Models/Eloquent/Shop/Category.php
<?php

namespace App\Models\Shop;

use App\Models\Shop\Translate\Category as CategoryTranslate;
use App\Models\Shop\Belongs\CategoriesProperties;
use Kalnoy\Nestedset\NodeTrait;
use App\Models\Shop\Property;

/**
 * Category
 * @package App\Models\Shop
 */
class Category extends \App\Models\Model
{
    use NodeTrait;

    const SALE_ALIAS = 'sale';
    const KYIV_ONLY_ALIAS = 'kyiv-only';

    /**
     * @var string
     */
    protected $table = 'shop_categories';

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function properties()
    {
        return $this->belongsToMany(Property::class, CategoriesProperties::getTableName(), 'category_id', 'property_id')
            ->withPivot('order');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function filterProperties()
    {
        return $this->belongsToMany(Property::class, CategoriesProperties::getTableName(), 'category_id', 'property_id')
            ->withPivot('order')->where('is_filter', 1);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function translations()
    {
        return $this->hasMany(CategoryTranslate::class, 'category_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function parent()
    {
        return $this->hasOne(Category::class, 'id', 'parent_id')->with(['translations']);
    }

    /**
     *  Переводы
     *
     * @param $query
     * @return mixed
     */
    public function scopeTranslates($query)
    {
        return $query->with(['translations']);
    }

    /**
     * Scope visible
     *
     * @param $query
     * @param int $scope
     * @return mixed
     */
    public function scopeVisible($query, $scope = 1)
    {
        return $query->where('visible', $scope);
    }

    /**
     * Все данные по категории
     *
     * @param $query
     * @return mixed
     */
    public function scopeTotal($query)
    {
        return $query->with([
            'translations',
            'parent' => function ($query) {
                $query->with(['translations']);
            },
            'properties' => function ($query) {
                $query->orderBy('order', 'asc');
                $query->with('translations');
                $query->with(['values' => function($query) {
                    $query->orderBy('order', 'asc');
                    $query->with('translations');
                }]);
            }
        ]);
    }

}

app/Models/Eloquent/Shop/Coupon.php
<?php

namespace App\Models\Shop;

use App\Models\Model;

/**
 * Coupon
 * @package App\Models\Shop
 */
class Coupon extends Model
{
    /**
     * @var string
     */
    protected $table = 'shop_coupons';

    /**
     * Сортировка desc
     *
     * @param $query
     * @return mixed
     */
    public function scopeOrderDesc($query)
    {
        return $query->orderBy('created_at', 'desc');
    }

    /**
     * Сортировка asc
     *
     * @param $query
     * @return mixed
     */
    public function scopeOrderAsc($query)
    {
        return $query->orderBy('created_at', 'asc');
    }
}

app/Models/Eloquent/Shop/Delivery.php
<?php

namespace App\Models\Shop;

/**
 * Delivery
 * @package App\Models\Shop
 */
class Delivery extends \App\Models\Model
{
    /**
     * @var string
     */
    protected $table = 'shop_checkout_delivery';

    /**
     * @var array
     */
    protected $dates = ['date', 'created_at', 'updated_at'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function checkout()
    {
        return $this->hasOne(Checkout::class, 'checkout_id', 'id');
    }
}

resources/views/backend/basic/shop/landings/_ajax_index.blade.php
@php
/**@var App\Modules\LandingModule\Models\LandingModel[] $landings */
@endphp
<div class="panel panel-default">
    <div class="panel-heading">
        <h5 class="panel-title">{{ trans('shop.landings.all') }}</h5>
        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="reload" data-url="{{ URL::full() }}" data-selector="#grid-landings"></a></li>
            </ul>
        </div>
    </div>
    <div class="table-responsive">
        <div style="margin: 10px;">
            <div class="row" style="margin-bottom: 10px; font-weight: bold;  border-bottom: 1px solid #a9a9a9; padding-bottom: 10px">
                <div class="col-md-3">{{ trans('shop.landings.link.title') }}</div>
                <div class="col-md-3">{{ trans('landings.status.noindex') }}</div>
                <div class="col-md-2">{{ trans('landings.date.created') }}</div>
                <div class="col-md-2">{{ trans('landings.date.updated') }}</div>
                <div class="col-md-2"></div>
            </div>
            @forelse($landings as $landing)
                <div class="row" style="padding: 10px">
                    <div class="col-md-3"><a href="{{ route('backend.shop.landings.destroy', $landing) }}">{{$landing->getUrl()}}</a></div>
                    <div class="col-md-3">{{$landing->getNoIndex()}}</div>
                    <div class="col-md-2">{!! DateTimeHelper::toFullDateTime($landing->created_at)?: trans('app.no-data') !!}</div>
                    <div class="col-md-2">{!! DateTimeHelper::toFullDateTime($landing->updated_at)?: trans('app.no-data') !!}</div>
                    <div class="col-md-2">
                        <ul class="icons-list">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="icon-cog"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li>
                                        <a href="{{ route('backend.shop.landings.edit', $landing) }}">
                                            <i class="icon-pencil"></i> {{ trans('app.edit') }}
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{{ route('backend.shop.landings.destroy', $landing) }}"  data-confirm="{{ trans('app.confirm') }}" data-method="delete">
                                            <i class="icon-close2"></i> {{ trans('app.delete') }}
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            @empty
                <div class="col-md-12">{{ trans('app.no-data') }}</div>
            @endforelse
        </div>
    </div>
    <div class="datatable-footer">
        <div class="dataTables_info">
            @if ($landings->count())
                {{ trans('app.all records :total', ['total' => $landings->count()])  }}
            @endif
        </div>
{{--        @if ($landings->count())--}}
{{--            @include('_pagination', ['paginator' => $landings])--}}
{{--        @endif--}}
    </div>
</div>

resources/views/backend/basic/shop/landings/create.blade.php
@extends('layouts.main')

@section('title', trans('shop.landings.create'))

@section('page-title')
    <h4>{{ trans('shop.landings.control') }}</h4>
@stop

@section('breadcrumbs')
    {{ Widget::run('Breadcrumbs', [
        trans('shop.shop'),
        '<a href="'.route('backend.shop.landings.index').'">'.trans('shop.landings.all').'</a>',
        trans('app.create'),
    ]) }}
@stop

@section('heading-elements')
@stop

@section('content')

    {{ Form::open(['route' => ['backend.shop.landings.store']]) }}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h6>{{ trans('shop.landings.create') }}</h6>
            </div>
            <div class="panel-body">
                @include('shop.landings._form')
            </div>
            <div class="panel-footer">
                <div class="heading-elements">
                    {{Form::submit(trans('app.save'), ['class' => 'btn btn-success heading-btn pull-left legitRipple'])}}
                </div>
            </div>
        </div>
    {{ Form::close() }}

@stop

resources/views/backend/basic/shop/landings/edit.blade.php
@extends('layouts.main')

@section('title', trans('shop.landings.edit'))

@section('page-title')
    <h4>{{ trans('shop.landings.control') }}</h4>
@stop

@section('breadcrumbs')
    {{ Widget::run('Breadcrumbs', [
        trans('shop.shop'),
        '<a href="'.route('backend.shop.landings.index').'">'.trans('shop.landings.all').'</a>',
        trans('app.edit'),
    ]) }}
@stop

@section('heading-elements')
    <a href="{{ route('backend.shop.landings.create') }}" class="btn btn-link btn-float has-text">
        <i class="icon-plus-circle2 text-primary"></i><span>{{ trans('app.create') }}</span>
    </a>
@stop

@section('content')

    {{ Form::open(['route' => ['backend.shop.landings.update', $landing], 'method' => 'PUT']) }}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h6>{{ trans('shop.landings.edit') }}</h6>
            </div>
            <div class="panel-body">
                @include('shop.landings._form')
            </div>
            <div class="panel-footer">
                <div class="heading-elements">
                    {{Form::submit(trans('app.save'), ['class' => 'btn btn-success heading-btn pull-left legitRipple'])}}
                </div>
            </div>
        </div>
    {{ Form::close() }}

@stop

resources/views/backend/basic/shop/landings/index.blade.php
@extends('layouts.main')

@section('title', trans('shop.landings.control'))

@section('page-title')
    <h4>{{ trans('shop.landings.control') }}</h4>
@stop

@section('breadcrumbs')
    {{ Widget::run('Breadcrumbs', [
        trans('shop.shop'),
        '<a href="'.route('backend.shop.landings.index').'">'.trans('shop.landings.all').'</a>',
    ]) }}
@stop

@section('heading-elements')
    <a href="{{ route('backend.shop.landings.create') }}" class="btn btn-link btn-float has-text">
        <i class="icon-plus-circle2 text-primary"></i><span>{{ trans('app.create') }}</span>
    </a>
@stop

@section('content')

    <div id="grid-landings">
        @include('shop.landings._ajax_index')
    </div>

@stop