app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Admin routes
|--------------------------------------------------------------------------
*/
Route::match(['GET', 'POST'], '/auth', [
    'prefix' => 'backend',
    'as' => 'backend.auth.login',
    'uses' => 'Backend\User\AuthController@login',
    'middleware' => ['web', 'language:backend', 'backend', 'setTheme:backend']
]);

Route::group(['prefix' => 'backend', 'namespace' => 'Backend', 'middleware' => ['web', 'language:backend', 'backend', 'auth:backend', 'setTheme:backend']], function () {

    // Site
    Route::get('/', ['as' => 'backend.site.index', 'uses' => 'SiteController@index']);
    Route::get('/page/logs', ['as' => 'backend.site.logs', 'uses' => 'SiteController@logs']);
    Route::match(['GET', 'POST'], '/page/settings', ['as' => 'backend.site.settings', 'uses' => 'SiteController@settings']);


    // Languages
    Route::get('/set-lang/{lang}', ['as' => 'backend.site.set-lang', 'uses' => 'SiteController@setLang']);
    Route::get('/languages/translations/{id}', ['as' => 'backend.languages.translations', 'uses' => 'LanguagesController@translations']);
    Route::put('/languages/translationUpdate', ['as' => 'backend.languages.translationsUpdate', 'uses' => 'LanguagesController@translationsUpdate']);

    // Modules
    Route::resource('contents', 'ContentsController');
    Route::resource('cities', 'CitiesController');
    // Route::resource('widgets', 'WidgetsController');
    Route::resource('seo', 'SeoController');
    Route::resource('languages', 'LanguagesController');
    Route::resource('currencies', 'CurrenciesController');
    //Route::resource('access', 'AccessController');
    Route::resource('reviews', 'ReviewsController');

    // Plugins
    Route::resource('plugins', 'PluginsController');
    Route::get('/plugins/control/{id}', [
        'as' => 'backend.plugins.control',
        'uses' => 'PluginsController@control'
    ]);

    // Content Extra
    Route::post('/contents/upload', ['as' => 'backend.contents.upload', 'uses' => 'ContentsController@upload']);
    Route::post('/contents/upload/images/{content}', ['as' => 'backend.content.images.upload', 'uses' => 'ContentImagesController@upload']);
    Route::resource('contentImages', 'ContentImagesController', ['only' => [
        'edit', 'update', 'destroy'
    ]]);

    // Help
    Route::get('/help', ['as' => 'backend.help.index', 'uses' => 'HelpController@index']);

    // Shop
    Route::group(['prefix' => 'shop', 'namespace' => 'Shop'], function ()
    {
        Route::get('/filter', ['as' => 'backend.shop.filter.index', 'uses' => 'FilterController@index']);

        Route::resource('checkoutProducts', 'CheckoutProductsController', ['only' => [
            'index', 'store', 'update', 'destroy'
        ]]);

        Route::resource('categories', 'CategoriesController');
        Route::resource('checkouts', 'CheckoutsController');
        Route::resource('coupons', 'CouponsController');
        Route::resource('landings', 'LandingsController');
        Route::resource('discounts', 'DiscountsController');
        Route::resource('products', 'ProductsController');
        Route::post('/products/{id}/files', ['as' => 'backend.products.files', 'uses' => 'ProductsController@files']);
        Route::post('/products/{id}/filter', ['as' => 'backend.products.filter', 'uses' => 'ProductsController@filter']);
        Route::post('/products/{id}/filter-param', ['as' => 'backend.products.filter.param', 'uses' => 'ProductsController@filterParam']);

        Route::resource('properties', 'PropertiesController', ['only' => [
            'index', 'create', 'store', 'edit', 'update', 'destroy'
        ]]);
        Route::resource('values', 'ValuesController', ['only' => [
            'store', 'update', 'destroy', 'create', 'edit'
        ]]);
        Route::resource('images', 'ImagesController', ['only' => [
            'edit', 'update', 'destroy'
        ]]);
        Route::post('/{id}/images/upload', ['as' => 'backend.shop.images.upload', 'uses' => 'ImagesController@upload']);
        Route::post('/{id}/images/order', ['as' => 'backend.shop.images.order', 'uses' => 'ImagesController@order']);
    });

    // Media
    Route::group(['prefix' => 'media', 'namespace' => 'Media'], function ()
    {
        Route::resource('videos', 'VideosController');
        Route::resource('images', 'ImagesController', ['only' => [
            'index', 'edit', 'update', 'destroy'
        ]]);
        Route::post('/images/upload', ['as' => 'backend.media.images.upload', 'uses' => 'ImagesController@upload']);
    });

    // User
    Route::group(['prefix' => 'user', 'namespace' => 'User'], function ()
    {
        // Auth
        Route::get('/logout', ['as' => 'backend.auth.logout', 'uses' => 'AuthController@logout']);

        Route::resource('users', 'UsersController');
        Route::post('users/{id}/restore', 'UsersController@restore')->name('backend.user.users.restore');
    });

    Route::group(['prefix' => 'plugins', 'namespace' => 'Plugins'], function () {

        // Slider
        Route::get('/slider/edit/{id}', [
            'as' => 'backend.plugins.slider.edit',
            'uses' => '\App\Plugins\Slider\Backend\SliderController@edit'
        ]);
        Route::post('/slider/update/{id}', [
            'as' => 'backend.plugins.slider.update',
            'uses' => '\App\Plugins\Slider\Backend\SliderController@update'
        ]);

        Route::get('/slider/destroy/{id}', [
            'as' => 'backend.plugins.slider.destroy',
            'uses' => '\App\Plugins\Slider\Backend\SliderController@destroy'
        ]);

        Route::resource('text', '\App\Plugins\Text\Backend\TextController');
    });

});

/*
|--------------------------------------------------------------------------
| App routes
|--------------------------------------------------------------------------
*/
Route::group(['middleware' => ['guest', 'web']], function () {
    Route::group(['prefix' => 'signin', 'as' => 'guest.'], function () {
        Route::get('{profile_type}', 'OAuthController@redirectToProvider')->name('oauth.redirect');
        Route::get('{profile_type}/callback', 'OAuthController@handleProviderCallback')->name('oauth.callback');
        Route::post('{profile_type}/signup', 'OAuthController@auth')->name('oauth.signup');
    });
});

$frontend_attr = ['middleware' => ['web', 'frontend', 'language:frontend', 'setTheme:default']];
$locale = Request::segment(1);

if(Translate::getLangByLocale($locale) && empty(Translate::getLangByLocale($locale)['default'])) {
    $frontend_attr['prefix'] = $locale;
}


//TODO: fix this route (same route in Payment group doesn't work)

Route::match(['get', 'post'], '/platon/callback', ['as' => 'platon.callback', 'uses' => 'Payment\PlatonController@callback']);

Route::group($frontend_attr, function () {

    // Site
    Route::get('/badbrowser', ['as' => 'site.badbrowser', 'uses' => 'SiteController@badbrowser']);
    Route::get('/contacts', ['as' => 'pages.contacts', 'uses' => 'SiteController@getContacts']);
    //Route::get('/sitemap.xml', ['as' => 'site.sitemap', 'uses' => 'SiteController@sitemap']);
    Route::get('/statics/js-data', ['uses' => 'SiteController@jsData']);

    Route::post('/contacts', ['as' => 'pages.contacts', 'uses' => 'SiteController@postContacts']);

    Route::get('/photos', ['as' => 'pages.photos', 'uses' => 'SiteController@photos']);
    Route::get('/videos', ['as' => 'pages.videos', 'uses' => 'SiteController@videos']);
    Route::get('/customorder', ['as' => 'pages.customorder', 'uses' => 'SiteController@getСustomorder']);
    Route::post('/customorder', ['as' => 'pages.customorder', 'uses' => 'SiteController@postСustomorder']);

    Route::get('/set-curr/{curr}', ['as' => 'site.set-curr', 'uses' => 'SiteController@setCurrency']);

    Route::get('/search', ['as' => 'product.search', 'uses' => 'ProductController@getSearch']);

    Route::get('/404.html', ['as' => 'error.404', 'uses' => 'SiteController@notFound']);



    Route::group(['middleware' => ['guest']], function () {

        // Login
        Route::get('/signin', ['uses' => 'GuestController@getSignin', 'as' => 'guest.signin']);
        Route::post('/signin', ['uses' => 'GuestController@postSignin', 'as' => 'guest.signin']);

        // Registration
        Route::get('/signup', ['uses' => 'GuestController@getSignup', 'as' => 'guest.signup']);
        Route::post('/signup', ['uses' => 'GuestController@postSignup', 'as' => 'guest.signup']);

        // Password Reset
        Route::get('/password/reset/{token?}', ['uses' => 'GuestController@getReset', 'as' => 'guest.password-reset']);
        Route::post('/password/email', ['uses' => 'GuestController@postEmail', 'as' => 'guest.password-email']);
        Route::post('/password/reset', ['uses' => 'GuestController@postReset', 'as' => 'guest.password-reset']);
    });

    // Email Confirmation Form
    Route::get('/signup/email-confirmation', [
        'uses' => 'GuestController@getConfirmForm',
        'as' => 'email_confirmation_form'
    ]);

    // Email Confirmation
    Route::get('/signup/email-confirm', [
        'uses' => 'GuestController@getConfirm',
        'as' => 'email_confirm'
    ]);

    Route::post('/buy-now', ['as' => 'cart.buy-now', 'uses' => 'CartController@postBuyNow']);

    Route::group(['middleware' => ['auth:web']], function () {
        // Аккаунт
        Route::get('/account', ['as' => 'user.index', 'uses' => 'UserController@index']);
        Route::post('/main-info', ['as' => 'user.main-info', 'uses' => 'UserController@postMainInfo']);
        Route::post('/manage-password', ['as' => 'user.manage-password', 'uses' => 'UserController@postManagePassword']);
        Route::post('/change-email', ['as' => 'user.change-email', 'uses' => 'UserController@postChangeEmail']);

        // История заказов

resources/views/backend/basic/languages/_ajax_index.blade.php
<div class="panel panel-default">
    <div class="panel-heading">
        <h5 class="panel-title">{{ trans('languages.languages') }}</h5>
        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="reload" data-url="{{ URL::full() }}" data-selector="#grid-languages"></a></li>
            </ul>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table datatable-basic table-hover">
            <thead>
            <tr>
                <th>{{ trans('languages.attr.locale') }}</th>
                <th>{{ trans('languages.attr.name') }}</th>
                <th>{{ trans('languages.attr.default') }}</th>
                <th>{{ trans('languages.attr.active') }}</th>
                <th class="text-center td-control">{{ trans('app.actions') }}</th>
            </tr>
            </thead>
            <tbody>
                @forelse($languages as $language)
                    <tr>
                        <td class="td-name">{{ $language->locale }}</td>
                        <td>{{ $language->name }}</td>
                        <td class="td-boolean">{{ Widget::run('BooleanView', ['value' => $language->default]) }}</td>
                        <td class="td-boolean">{{ Widget::run('BooleanView', ['value' => $language->active]) }}</td>
                        <td class="td-control text-center">
                            <ul class="icons-list">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <i class="icon-cog"></i>
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li><a href="{{ route('backend.languages.edit', $language) }}"><i class="icon-pencil"></i> {{ trans('app.edit') }}</a></li>
                                        <li><a href="{{ route('backend.languages.destroy', $language) }}" data-confirm="{{ trans('app.confirm') }}" data-method="delete">
                                            <i class="icon-close2"></i> {{ trans('app.delete') }}</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="5">{{ trans('app.no-data') }}</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>
    <div class="datatable-footer">
        <div class="dataTables_info">
            @if ($languages->count())
                {{ trans('app.all records :total', ['total' => $languages->count()])  }}
            @endif
        </div>
    </div>
</div>

resources/views/backend/basic/languages/_form.blade.php
<div class="panel panel-default">
    <div class="panel-heading">
        <h5 class="panel-title">{{ trans('languages.language') }}</h5>
    </div>
    <div class="panel-body">
        <div class="col-sm-2">
            <div class="form-group required {{ $errors->has('locale') ? 'has-error' : '' }}">
                {{ Form::label('locale', trans('languages.attr.locale'), ['class' => 'control-label']) }}
                {{ Form::text('locale', isset($language->locale) ? $language->locale : null, ['class' => 'form-control']) }}
                <div class="help-block">{{ $errors->has('locale') ? $errors->first('locale') : '' }}</div>
            </div>
        </div>
        <div class="col-sm-2">
            <div class="form-group required {{ $errors->has('name') ? 'has-error' : '' }}">
                {{ Form::label('name', trans('languages.attr.name'), ['class' => 'control-label']) }}
                {{ Form::text('name', isset($language->name) ? $language->name : null, ['class' => 'form-control']) }}
                <div class="help-block">{{ $errors->has('name') ? $errors->first('name') : '' }}</div>
            </div>
        </div>
        <div class="col-sm-12">
            <div class="row">
                <div class="col-sm-2">
                    <div class="form-group checkbox checkbox-switchery {{ $errors->has('active') ? 'has-error' : '' }}">
                        <label>
                            {{ Form::checkbox('active', 'on', !empty($language->active) ? $language->active : null, [
                                'class' => 'switchery',
                            ]) }}
                            {{ trans('languages.attr.active') }}
                            <div class="help-block">{{ $errors->has('active') ? $errors->first('active') : '' }}</div>
                        </label>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group checkbox checkbox-switchery {{ $errors->has('default') ? 'has-error' : '' }}">
                        <label>
                            {{ Form::checkbox('default', 'on', !empty($language->default) ? $language->default : null, [
                                'class' => 'switchery',
                            ]) }}
                            {{ trans('languages.attr.default') }}
                            <div class="help-block">{{ $errors->has('default') ? $errors->first('default') : '' }}</div>
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <div class="heading-elements">
            <button type="submit" class="btn btn-success heading-btn pull-left legitRipple">{{ trans('app.save') }}</button>
        </div>
    </div>
</div>

resources/views/backend/basic/languages/create.blade.php
@extends('layouts.main')

@section('title', trans('languages.create'))

@section('page-title')
    <h4>{{ trans('languages.control') }}</h4>
@stop

@section('breadcrumbs')
    {{ Widget::run('Breadcrumbs', [
        '<a href="'.route('backend.languages.index').'">'.trans('languages.all').'</a>',
        trans('app.create')
    ]) }}
@stop

@section('heading-elements')
    <a href="{{ route('backend.languages.create') }}" class="btn btn-link btn-float has-text">
        <i class="icon-plus-circle2 text-primary"></i><span>{{ trans('app.create') }}</span>
    </a>
@stop

@section('content')

    {{ Form::open(['route' => ['backend.languages.store']]) }}

        @include('languages._form')

    {{ Form::close() }}

@stop

resources/views/backend/basic/languages/edit.blade.php
@extends('layouts.main')

@section('title', trans('languages.edit'))

@section('page-title')
    <h4>{{ trans('languages.control') }}</h4>
@stop

@section('breadcrumbs')
    {{ Widget::run('Breadcrumbs', [
        '<a href="'.route('backend.languages.index').'">'.trans('languages.all').'</a>',
        $language->name
    ]) }}
@stop

@section('heading-elements')
    <a href="{{ route('backend.languages.create') }}" class="btn btn-link btn-float has-text">
        <i class="icon-plus-circle2 text-primary"></i><span>{{ trans('app.create') }}</span>
    </a>

    <a href="{{ route('backend.languages.translations', ['id' => $language]) }}" class="btn btn-link btn-float has-text">
        <i class="icon-graduation2 text-primary"></i><span>{{ trans('languages.translates') }}</span>
    </a>
@stop

@section('content')

    {{ Form::open(['route' => ['backend.languages.update', $language], 'method' => 'PUT']) }}

        @include('languages._form')

    {{ Form::close() }}

@stop

resources/views/backend/basic/languages/index.blade.php
@extends('layouts.main')

@section('title', trans('languages.control'))

@section('page-title')
    <h4>{{ trans('languages.control') }}</h4>
@stop

@section('breadcrumbs')
    {{ Widget::run('Breadcrumbs', [
        '<a href="'.route('backend.languages.index').'">'.trans('languages.all').'</a>'
    ]) }}
@stop

@section('heading-elements')
    <a href="{{ route('backend.languages.create') }}" class="btn btn-link btn-float has-text">
        <i class="icon-plus-circle2 text-primary"></i><span>{{ trans('app.create') }}</span>
    </a>

    <a href="{{ route('backend.languages.translations', ['id' => $defaultLanguage->id, 'with' => $notDefaultLanguage ? $notDefaultLanguage->id : null]) }}" class="btn btn-link btn-float has-text">
        <i class="icon-graduation2 text-primary"></i><span>{{ trans('languages.translates') }}</span>
    </a>
@stop

@section('content')

    <div id="grid-languages">
        @include('languages._ajax_index')
    </div>

@stop

resources/views/backend/basic/languages/translations.blade.php
@extends('layouts.main')

@section('title', trans('languages.translations-control'))

@section('page-title')
    <h4>{{ trans('languages.translations-control') }}</h4>
@stop

@section('breadcrumbs')
    {{ Widget::run('Breadcrumbs', [
        '<a href="'.route('backend.languages.index').'">'.trans('languages.all').'</a>'
    ]) }}
@stop

@section('content')
    <div class="row">
        <div class="col-sm-5">
            <div class="panel panel-default ">
                <div class="panel-heading">
                    <h5 class="panel-title">{{ trans('app.filter') }}</h5>
                </div>
                {{ Form::open(['method' => 'GET']) }}
                    <div class="panel-body">
                        <div class="form-group col-sm-6 no-margin-bottom">
                            <label for="language_to_edit">{{ trans('languages.group') }}</label>
                            {{ Form::select('group', $groups, Request::query('group'), [
                                'id' => 'group',
                                'name' => 'group',
                                'class' => 'select form-control'
                            ]) }}
                        </div>
                        <div class="form-group col-sm-6 no-margin-bottom">
                            <label for="with">{{ trans('languages.secondary-language') }}</label>
                            {{ Form::select('with',
                                $allExcept->pluck('name', 'id')->prepend(trans('app.no'), 0)->toArray(), Request::query('with'), [
                                'class' => 'select form-control'
                            ]) }}
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="heading-elements">
                            <button type="submit" class="btn btn-primary heading-btn pull-left legitRipple">
                                {{ trans('app.btn.filter') }}
                            </button>
                        </div>
                    </div>
                {{ Form::close() }}
            </div>
        </div>
        {{ Form::open(['route' => ['backend.languages.translationsUpdate'], 'method' => 'PUT']) }}
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h5 class="panel-title">{{ trans('app.translations') }}</h5>
                    </div>
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>{{ trans('languages.attr.constant') }}</th>
                            <th>{{ $mainLanguage->name }}</th>
                            @if (isset($semiLanguage))
                                <th>{{ $semiLanguage->name }}</th>
                            @endif
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($formTranslations as $key => $translation)
                            <tr>
                                <td class="text-left" style="max-width: 350px; width: 350px;">{{ $translation['constant'] }}</td>
                                <td class="text-left">
                                    <div class="form-group">
                                        <?php
                                            $inputNameId = "translates[{$mainLanguage->locale}][{$translation['group']}][{$translation['constant']}][id]";
                                            $inputNameGroup = "translates[{$mainLanguage->locale}][{$translation['group']}][{$translation['constant']}][group]";
                                            $inputNameConst = "translates[{$mainLanguage->locale}][{$translation['group']}][{$translation['constant']}][constant]";
                                            $inputName = "translates[{$mainLanguage->locale}][{$translation['group']}][{$translation['constant']}][text]";
                                        ?>
                                        {{ Form::hidden($inputNameId, $translation['mainId']) }}
                                        {{ Form::hidden($inputNameGroup, $translation['group']) }}
                                        {{ Form::hidden($inputNameConst, $translation['constant']) }}
                                        {{ Form::textarea($inputName, $translation['mainTranslate'], ['class' => 'form-control', 'rows' => '2']) }}
                                    </div>
                                </td>
                                @if (isset($semiLanguage))
                                    <td class="text-left">
                                        <div class="form-group">
                                            @if ($semiLanguage)
                                                <?php
                                                    $inputNameId = "translates[{$semiLanguage->locale}][{$translation['group']}][{$translation['constant']}][id]";
                                                    $inputNameGroup = "translates[{$semiLanguage->locale}][{$translation['group']}][{$translation['constant']}][group]";
                                                    $inputNameConst = "translates[{$semiLanguage->locale}][{$translation['group']}][{$translation['constant']}][constant]";
                                                    $inputName = "translates[{$semiLanguage->locale}][{$translation['group']}][{$translation['constant']}][text]";
                                                ?>
                                                {{ Form::hidden($inputNameId, $translation['semiId']) }}
                                                {{ Form::hidden($inputNameGroup, $translation['group']) }}
                                                {{ Form::hidden($inputNameConst, $translation['constant']) }}
                                                {{ Form::textarea($inputName, $translation['semiTranslate'], ['class' => 'form-control', 'rows' => '2']) }}
                                            @endif
                                        </div>
                                    </td>
                                @endif
                            </tr>
                        @empty
                            <tr>
                                <td colspan="3">{{ trans('app.no-data') }}</td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                    <div class="table-footer"></div>
                    <div class="panel-footer">
                        <div class="heading-elements">
                            @if (!empty($formTranslations))
                                <button type="submit" class="btn btn-success heading-btn pull-left legitRipple">
                                    {{ trans('app.save') }}
                                </button>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        {{ Form::close() }}
    </div>
@stop