app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Admin routes
|--------------------------------------------------------------------------
*/
Route::match(['GET', 'POST'], '/auth', [
    'prefix' => 'backend',
    'as' => 'backend.auth.login',
    'uses' => 'Backend\User\AuthController@login',
    'middleware' => ['web', 'language:backend', 'backend', 'setTheme:backend']
]);

Route::group(['prefix' => 'backend', 'namespace' => 'Backend', 'middleware' => ['web', 'language:backend', 'backend', 'auth:backend', 'setTheme:backend']], function () {

    // Site
    Route::get('/', ['as' => 'backend.site.index', 'uses' => 'SiteController@index']);
    Route::get('/page/logs', ['as' => 'backend.site.logs', 'uses' => 'SiteController@logs']);
    Route::match(['GET', 'POST'], '/page/settings', ['as' => 'backend.site.settings', 'uses' => 'SiteController@settings']);


    // Languages
    Route::get('/set-lang/{lang}', ['as' => 'backend.site.set-lang', 'uses' => 'SiteController@setLang']);
    Route::get('/languages/translations/{id}', ['as' => 'backend.languages.translations', 'uses' => 'LanguagesController@translations']);
    Route::put('/languages/translationUpdate', ['as' => 'backend.languages.translationsUpdate', 'uses' => 'LanguagesController@translationsUpdate']);

    // Modules
    Route::resource('contents', 'ContentsController');
    Route::resource('cities', 'CitiesController');
    // Route::resource('widgets', 'WidgetsController');
    Route::resource('seo', 'SeoController');
    Route::resource('languages', 'LanguagesController');
    Route::resource('currencies', 'CurrenciesController');
    //Route::resource('access', 'AccessController');
    Route::resource('reviews', 'ReviewsController');

    // Plugins
    Route::resource('plugins', 'PluginsController');
    Route::get('/plugins/control/{id}', [
        'as' => 'backend.plugins.control',
        'uses' => 'PluginsController@control'
    ]);

    // Content Extra
    Route::post('/contents/upload', ['as' => 'backend.contents.upload', 'uses' => 'ContentsController@upload']);
    Route::post('/contents/upload/images/{content}', ['as' => 'backend.content.images.upload', 'uses' => 'ContentImagesController@upload']);
    Route::resource('contentImages', 'ContentImagesController', ['only' => [
        'edit', 'update', 'destroy'
    ]]);

    // Help
    Route::get('/help', ['as' => 'backend.help.index', 'uses' => 'HelpController@index']);

    // Shop
    Route::group(['prefix' => 'shop', 'namespace' => 'Shop'], function ()
    {
        Route::get('/filter', ['as' => 'backend.shop.filter.index', 'uses' => 'FilterController@index']);

        Route::resource('checkoutProducts', 'CheckoutProductsController', ['only' => [
            'index', 'store', 'update', 'destroy'
        ]]);

        Route::resource('categories', 'CategoriesController');
        Route::resource('checkouts', 'CheckoutsController');
        Route::resource('coupons', 'CouponsController');
        Route::resource('landings', 'LandingsController');
        Route::resource('discounts', 'DiscountsController');
        Route::resource('products', 'ProductsController');
        Route::post('/products/{id}/files', ['as' => 'backend.products.files', 'uses' => 'ProductsController@files']);
        Route::post('/products/{id}/filter', ['as' => 'backend.products.filter', 'uses' => 'ProductsController@filter']);
        Route::post('/products/{id}/filter-param', ['as' => 'backend.products.filter.param', 'uses' => 'ProductsController@filterParam']);

        Route::resource('properties', 'PropertiesController', ['only' => [
            'index', 'create', 'store', 'edit', 'update', 'destroy'
        ]]);
        Route::resource('values', 'ValuesController', ['only' => [
            'store', 'update', 'destroy', 'create', 'edit'
        ]]);
        Route::resource('images', 'ImagesController', ['only' => [
            'edit', 'update', 'destroy'
        ]]);
        Route::post('/{id}/images/upload', ['as' => 'backend.shop.images.upload', 'uses' => 'ImagesController@upload']);
        Route::post('/{id}/images/order', ['as' => 'backend.shop.images.order', 'uses' => 'ImagesController@order']);
    });

    // Media
    Route::group(['prefix' => 'media', 'namespace' => 'Media'], function ()
    {
        Route::resource('videos', 'VideosController');
        Route::resource('images', 'ImagesController', ['only' => [
            'index', 'edit', 'update', 'destroy'
        ]]);
        Route::post('/images/upload', ['as' => 'backend.media.images.upload', 'uses' => 'ImagesController@upload']);
    });

    // User
    Route::group(['prefix' => 'user', 'namespace' => 'User'], function ()
    {
        // Auth
        Route::get('/logout', ['as' => 'backend.auth.logout', 'uses' => 'AuthController@logout']);

        Route::resource('users', 'UsersController');
        Route::post('users/{id}/restore', 'UsersController@restore')->name('backend.user.users.restore');
    });

    Route::group(['prefix' => 'plugins', 'namespace' => 'Plugins'], function () {

        // Slider
        Route::get('/slider/edit/{id}', [
            'as' => 'backend.plugins.slider.edit',
            'uses' => '\App\Plugins\Slider\Backend\SliderController@edit'
        ]);
        Route::post('/slider/update/{id}', [
            'as' => 'backend.plugins.slider.update',
            'uses' => '\App\Plugins\Slider\Backend\SliderController@update'
        ]);

        Route::get('/slider/destroy/{id}', [
            'as' => 'backend.plugins.slider.destroy',
            'uses' => '\App\Plugins\Slider\Backend\SliderController@destroy'
        ]);

        Route::resource('text', '\App\Plugins\Text\Backend\TextController');
    });

});

/*
|--------------------------------------------------------------------------
| App routes
|--------------------------------------------------------------------------
*/
Route::group(['middleware' => ['guest', 'web']], function () {
    Route::group(['prefix' => 'signin', 'as' => 'guest.'], function () {
        Route::get('{profile_type}', 'OAuthController@redirectToProvider')->name('oauth.redirect');
        Route::get('{profile_type}/callback', 'OAuthController@handleProviderCallback')->name('oauth.callback');
        Route::post('{profile_type}/signup', 'OAuthController@auth')->name('oauth.signup');
    });
});

$frontend_attr = ['middleware' => ['web', 'frontend', 'language:frontend', 'setTheme:default']];
$locale = Request::segment(1);

if(Translate::getLangByLocale($locale) && empty(Translate::getLangByLocale($locale)['default'])) {
    $frontend_attr['prefix'] = $locale;
}


//TODO: fix this route (same route in Payment group doesn't work)

Route::match(['get', 'post'], '/platon/callback', ['as' => 'platon.callback', 'uses' => 'Payment\PlatonController@callback']);

Route::group($frontend_attr, function () {

    // Site
    Route::get('/badbrowser', ['as' => 'site.badbrowser', 'uses' => 'SiteController@badbrowser']);
    Route::get('/contacts', ['as' => 'pages.contacts', 'uses' => 'SiteController@getContacts']);
    //Route::get('/sitemap.xml', ['as' => 'site.sitemap', 'uses' => 'SiteController@sitemap']);
    Route::get('/statics/js-data', ['uses' => 'SiteController@jsData']);

    Route::post('/contacts', ['as' => 'pages.contacts', 'uses' => 'SiteController@postContacts']);

    Route::get('/photos', ['as' => 'pages.photos', 'uses' => 'SiteController@photos']);
    Route::get('/videos', ['as' => 'pages.videos', 'uses' => 'SiteController@videos']);
    Route::get('/customorder', ['as' => 'pages.customorder', 'uses' => 'SiteController@getСustomorder']);
    Route::post('/customorder', ['as' => 'pages.customorder', 'uses' => 'SiteController@postСustomorder']);

    Route::get('/set-curr/{curr}', ['as' => 'site.set-curr', 'uses' => 'SiteController@setCurrency']);

    Route::get('/search', ['as' => 'product.search', 'uses' => 'ProductController@getSearch']);

    Route::get('/404.html', ['as' => 'error.404', 'uses' => 'SiteController@notFound']);



    Route::group(['middleware' => ['guest']], function () {

        // Login
        Route::get('/signin', ['uses' => 'GuestController@getSignin', 'as' => 'guest.signin']);
        Route::post('/signin', ['uses' => 'GuestController@postSignin', 'as' => 'guest.signin']);

        // Registration
        Route::get('/signup', ['uses' => 'GuestController@getSignup', 'as' => 'guest.signup']);
        Route::post('/signup', ['uses' => 'GuestController@postSignup', 'as' => 'guest.signup']);

        // Password Reset
        Route::get('/password/reset/{token?}', ['uses' => 'GuestController@getReset', 'as' => 'guest.password-reset']);
        Route::post('/password/email', ['uses' => 'GuestController@postEmail', 'as' => 'guest.password-email']);
        Route::post('/password/reset', ['uses' => 'GuestController@postReset', 'as' => 'guest.password-reset']);
    });

    // Email Confirmation Form
    Route::get('/signup/email-confirmation', [
        'uses' => 'GuestController@getConfirmForm',
        'as' => 'email_confirmation_form'
    ]);

    // Email Confirmation
    Route::get('/signup/email-confirm', [
        'uses' => 'GuestController@getConfirm',
        'as' => 'email_confirm'
    ]);

    Route::post('/buy-now', ['as' => 'cart.buy-now', 'uses' => 'CartController@postBuyNow']);

    Route::group(['middleware' => ['auth:web']], function () {
        // Аккаунт
        Route::get('/account', ['as' => 'user.index', 'uses' => 'UserController@index']);
        Route::post('/main-info', ['as' => 'user.main-info', 'uses' => 'UserController@postMainInfo']);
        Route::post('/manage-password', ['as' => 'user.manage-password', 'uses' => 'UserController@postManagePassword']);
        Route::post('/change-email', ['as' => 'user.change-email', 'uses' => 'UserController@postChangeEmail']);

        // История заказов

app/Models/Eloquent/Plugin.php
<?php

namespace App\Models;

/**
 * Plugin
 * @package App\Models
 */
class Plugin extends \App\Models\Model
{
    protected $table = 'plugins';

    const TYPE_SLIDER = 'slider';
    const TYPE_TEXT = 'text';

    /**
     * Сортировка DESC
     *
     * @param $query
     * @return mixed
     */
    public function scopeOrderDesc($query)
    {
        return $query->orderBy('created_at', 'desc');
    }

    /**
     * Сортировка ASC
     *
     * @param $query
     * @return mixed
     */
    public function scopeOrderAsc($query)
    {
        return $query->orderBy('created_at', 'asc');
    }

    /**
     * Подтверждение
     *
     * @param $query
     * @param int $state
     * @return mixed
     */
    public function scopeVisible($query, $state = 1)
    {
        return $query->where('visible', $state);
    }

    /**
     * @return array
     */
    public static function getTypesArray()
    {
        return [
            self::TYPE_SLIDER => trans('plugins.slider'),
            self::TYPE_TEXT => trans('plugins.text'),
        ];
    }
}

app/Http/Controllers/Backend/PluginsController.php
<?php

namespace App\Http\Controllers\Backend;

use Api\App\Contracts\Entities\PluginRepository as PluginInterface;
use App\Http\Requests\Backend\PluginRequest;
use App\Services\PluginService;
use Api\App\Storage\Condition;
use Request;
use Session;
use Route;

/**
 * Plugins Controller
 * @package App\Http\Controllers\Backend
 */
class PluginsController extends \App\Http\Controllers\Controller
{
    /**
     * @var PluginInterface
     */
    protected $pluginRepository;

    /**
     * @var PluginService
     */
    protected $pluginService;

    /**
     * @param PluginInterface $pluginRepository
     * @param PluginService $pluginService
     */
    public function __construct(
        PluginInterface $pluginRepository,
        PluginService $pluginService
    )
    {
        $this->pluginRepository = $pluginRepository;
        $this->pluginService = $pluginService;
    }

    /**
     * GET /backend/plugins
     * Display all of the plugins.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $condition = new Condition();
        $condition->pagination()
            ->limit(100);

        $plugins = $this->pluginRepository->findAll($condition);

        if (Request::ajax()) {
            return view('plugins._ajax_index', [
                'plugins' => $plugins
            ]);
        }

        return view('plugins.index', [
            'plugins' => $plugins
        ]);
    }

    /**
     * GET /backend/plugins/create
     * Display the form for creating a new widget.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('plugins.create');
    }

    /**
     * POST /backend/plugins
     * Store a new widget in storage.
     *
     * @param PluginRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(PluginRequest $request)
    {
        $result = $this->pluginService->save($request->all());

        if ($result) {
            Session::flash('success', trans('app.create_success'));
            return redirect(route('backend.plugins.index'));
        } else {
            Session::flash('danger', trans('app.critical_error'));
        }
        return redirect(route('backend.plugins.index'));
    }

    /**
     * POST /backend/plugins
     * Update a widget in storage.
     *
     * @param PluginRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(PluginRequest $request, $id)
    {
        if (!$plugin = $this->pluginRepository->findById($id)) {
            abort(404);
        }

        $result = $this->pluginService->save($request->all(), $plugin);

        if ($result) {
            Session::flash('success', trans('app.create_success'));
            return redirect(route('backend.plugins.index'));
        } else {
            Session::flash('danger', trans('app.critical_error'));
        }
        return redirect(route('backend.plugins.index'));
    }

    /**
     * GET /backend/plugins/1
     * Show a widget in storage.
     *
     * @param $id
     * @return \Illuminate\Routing\Redirector
     */
    public function show($id)
    {
        return redirect(route('backend.plugins.edit', ['id' => $id]));
    }

    /**
     * GET /backend/plugins/1/edit
     * Display the form for editing a widget.
     *
     * @param $id
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {
        if (!$plugin = $this->pluginRepository->findById($id)) {
            abort(404);
        }

        return view('plugins.edit', [
            'plugin' => $plugin
        ]);
    }

    /**
     * GET /backend/plugins/1/control
     * Display the form for editing a widget.
     *
     * @param $id
     * @return \Illuminate\View\View
     */
    public function control($id)
    {
        if (!$plugin = $this->pluginRepository->findById($id)) {
            abort(404);
        }

        $route = 'backend.plugins.' . $plugin->type . '.edit';

        if (!Route::has($route)) {
            abort(404);
        }

        return redirect(route($route, $plugin));
    }

    /**
     * DELETE /backend/plugins/1
     * Remove a plugin from storage.
     *
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        if (!$plugin = $this->pluginRepository->findById($id)) {
            abort(404);
        }

        if ($this->pluginService->delete($plugin)) {
            Session::flash('success', trans('app.delete_success'));
        } else {
            Session::flash('danger', trans('app.critical_error'));
        }

        return redirect(route('backend.plugins.index'));
    }
}

resources/views/backend/basic/plugins/_ajax_index.blade.php
<div class="panel panel-default">
    <div class="panel-heading">
        <h5 class="panel-title">{{ trans('plugins.plugins') }}</h5>
        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="reload" data-url="{{ URL::full() }}" data-selector="#grid-plugins"></a></li>
            </ul>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table datatable-basic table-hover">
            <thead>
            <tr>
                <th class="td-name">{{ trans('app.attr.type') }}</th>
                <th class="td-name">{{ trans('app.attr.alias') }}</th>
                <th>{{ trans('app.attr.description') }}</th>
                <th class="td-boolean">{{ trans('app.attr.visible') }}</th>
                <th class="text-center td-control">{{ trans('app.actions') }}</th>
            </tr>
            </thead>
            <tbody>
            @if ($plugins->count())
                @foreach ($plugins as $plugin)
                    <tr>
                        <td class="td-name"><strong>{{ $plugin->type }}</strong></td>
                        <td class="td-name"><strong>{{ $plugin->key }}</strong></td>
                        <td>{{ trim($plugin->description) ? $plugin->description : trans('app.no-data')}}</td>
                        <td class="td-boolean">{{ Widget::run('BooleanView', ['value' => $plugin->visible]) }}</td>
                        <td class="text-center">
                            <ul class="icons-list">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <i class="icon-cog"></i>
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li>
                                            <a href="{{ route('backend.plugins.control', $plugin) }}">
                                                <i class="icon-cog"></i> {{ trans('app.control') }}
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{{ route('backend.plugins.edit', $plugin) }}">
                                                <i class="icon-pencil"></i> {{ trans('app.edit') }}
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{{ route('backend.plugins.destroy', $plugin) }}"
                                               data-confirm="{{ trans('app.confirm') }}" data-method="delete">
                                                <i class="icon-cancel-circle2"></i> {{ trans('app.delete') }}
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </td>
                    </tr>
                @endforeach
            @else
                <tr>
                    <td colspan="6">{{ trans('app.no-data') }}</td>
                </tr>
            @endif
            </tbody>
        </table>
    </div>
    <div class="datatable-footer">
        <div class="dataTables_info">
            @if ($plugins->count())
                {{ trans('app.all records :total', ['total' => $plugins->total()])  }}
            @endif
        </div>
        @if ($plugins->count())
            @include('_pagination', ['paginator' => $plugins])
        @endif
    </div>
</div>

resources/views/backend/basic/plugins/_form.blade.php
<div class="panel panel-default">
    <div class="panel-heading">
        <h6 class="panel-title">{{ isset($plugin) ? trans('plugins.edit') : trans('plugins.create') }}</h6>
    </div>
    <div class="panel-body">
        @if (!isset($plugin))
            <div class="col-sm-3">
                <div class="form-group required">
                    {{ Form::label('key', trans('app.attr.type'), ['class' => 'control-label']) }}
                    {{ Form::select('type', [
                        'slider' => 'Слайдер',
                        'text' => 'Текст',
                    ], null, ['class' => 'select form-control']) }}
                    <div class="help-block">{{ $errors->has('type') ? $errors->first('type') : '' }}</div>
                </div>
            </div>
        @endif
        <div class="col-sm-3">
            <div class="form-group required {{ $errors->has('key') ? 'has-error' : '' }}">
                {{ Form::label('key', trans('app.attr.alias'), ['class' => 'control-label']) }}
                {{ Form::text('key', isset($plugin->key) ? $plugin->key : null, ['class' => 'form-control']) }}
                <div class="help-block">{{ $errors->has('key') ? $errors->first('key') : '' }}</div>
            </div>
        </div>
        <div class="col-sm-3">
            <br>
            <div class="checkbox checkbox-switchery">
                <label>
                    {{ Form::checkbox('visible', 'on', !empty($plugin->visible) ? $plugin->visible : null, [
                        'class' => 'switchery',
                    ]) }}
                    <div class="help-block">{{ $errors->has('visible') ? $errors->first('visible') : '' }}</div>
                    {{ trans('shop.product.product_visible') }}
                </label>
            </div>
        </div>
        <div class="col-sm-12">
            <div class="form-group required {{ $errors->has('description') ? 'has-error' : '' }}">
                {{ Form::label('description', trans('app.attr.description'), ['class' => 'control-label']) }}
                {{ Form::text('description', isset($plugin->description) ? $plugin->description : null, ['class' => 'form-control']) }}
                <div class="help-block">{{ $errors->has('description') ? $errors->first('description') : '' }}</div>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <div class="heading-elements">
            <button type="submit" class="btn btn-success heading-btn pull-left legitRipple">{{ trans('app.save')  }}</button>
        </div>
    </div>
</div>

resources/views/backend/basic/plugins/create.blade.php
@extends('layouts.main')

@section('title', trans('plugins.create'))

@section('page-title')
    <h4>{{ trans('plugins.control') }}</h4>
@stop

@section('breadcrumbs')
    {{ Widget::run('Breadcrumbs', [
        '<a href="'.route('backend.plugins.index').'">'.trans('plugins.plugins').'</a>',
        trans('app.create')
    ]) }}
@stop

@section('heading-elements')
    
@stop

@section('content')

    {{ Form::open(['route' => ['backend.plugins.store']]) }}
    @include('plugins._form')
    {{ Form::close() }}

@stop

resources/views/backend/basic/plugins/edit.blade.php
@extends('layouts.main')

@section('title', trans('plugins.update'))

@section('page-title')
    <h4>{{ trans('plugins.control') }}</h4>
@stop

@section('breadcrumbs')
    {{ Widget::run('Breadcrumbs', [
        '<a href="'.route('backend.plugins.index').'">'.trans('plugins.plugins').'</a>',
        trans('app.create')
    ]) }}
@stop

@section('heading-elements')
    
@stop

@section('content')

    {{ Form::open(['route' => ['backend.plugins.update', $plugin],'method' => 'PUT']) }}
    @include('plugins._form')
    {{ Form::close() }}

@stop

resources/views/backend/basic/plugins/index.blade.php
@extends('layouts.main')

@section('title', trans('plugins.control'))

@section('page-title')
    <h4>{{ trans('plugins.control') }}</h4>
@stop

@section('breadcrumbs')
    {{ Widget::run('Breadcrumbs', [
        '<a href="'.route('backend.plugins.index').'">'.trans('plugins.plugins').'</a>',
    ]) }}
@stop

@section('heading-elements')
    <a href="{{ route('backend.plugins.create') }}" class="btn btn-link btn-float has-text">
        <i class="icon-plus-circle2 text-primary"></i><span>{{ trans('app.create') }}</span>
    </a>
@stop

@section('content')

    <div id="grid-plugins">
        @include('plugins._ajax_index')
    </div>

@stop